name: nemesis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - umap-learn
  - matplotlib
  - seaborn
  - plotly
  - dash
  - networkx
  - jupyterlab
  - pytest
  - pip
  - pip:
      - nibabel
      - nilearn
      - factor_analyzer
      - pacmap
